#ifndef HW_RL78_GPIO_H
#define HW_RL78_GPIO_H

#include "hw/core/sysbus.h"

#define RL78_GPIO_REG_NUM (16)

typedef enum RL78_GPIO_MODE_TYPE {
    RL78_GPIO_MODE_TYPE_OUTPUT = 0,
    RL78_GPIO_MODE_TYPE_INPUT  = 1,
} RL78_GPIO_MODE_TYPE;

typedef enum RL78_GPIO_LEVEL {
    RL78_GPIO_LEVEL_LOW  = 0,
    RL78_GPIO_LEVEL_HIGH = 1,
} RL78_GPIO_LEVEL;

typedef enum RL78_GPIO_INPUT_MODE_TYPE {
    RL78_GPIO_INPUT_MODE_TYPE_CMOS = 0,
    RL78_GPIO_INPUT_MODE_TYPE_TTL  = 1,
} RL78_GPIO_INPUT_MODE_TYPE;

typedef enum RL78_GPIO_OUTPUT_MODE_TYPE {
    RL78_GPIO_OUTPUT_MODE_TYPE_NORMAL    = 0,
    RL78_GPIO_OUTPUT_MODE_TYPE_OPENDRAIN = 1,
} RL78_GPIO_OUTPUT_MODE_TYPE;

typedef enum RL78_GPIO_DIGITAL_INPUT_DISABLE_TYPE {
    RL78_GPIO_DIGITAL_INPUT_DISABLE_TYPE_ALLOW    = 0,
    RL78_GPIO_DIGITAL_INPUT_DISABLE_TYPE_DISALLOW = 1,
} RL78_GPIO_DIGITAL_INPUT_DISABLE_TYPE;

typedef enum RL78_GPIO_CONTROL_A_TYPE {
    RL78_GPIO_CONTROL_A_TYPE_DIGITAL = 0,
    RL78_GPIO_CONTROL_A_TYPE_ANALOG  = 1,
} RL78_GPIO_CONTROL_A_TYPE;

typedef enum RL78_GPIO_CONTROL_T_TYPE {
    RL78_GPIO_CONTROL_T_TYPE_DIGITAL     = 0,
    RL78_GPIO_CONTROL_T_TYPE_CAPACITANCE = 1,
} RL78_GPIO_CONTROL_T_TYPE;

typedef enum RL78_GPIO_CONTROL_E_TYPE {
    RL78_GPIO_CONTROL_E_TYPE_DIGITAL = 0,
    RL78_GPIO_CONTROL_E_TYPE_ELCL = 1,
}RL78_GPIO_CONTROL_E_TYPE;

typedef enum RL78_GPIO_REDIRECTION {
    RL78_GPIO_REDIRECTION_PATTERN_0 = 0,
    RL78_GPIO_REDIRECTION_PATTERN_1 = 1,
} RL78_GPIO_REDIRECTION;

typedef enum RL78_GPIO_GLOBAL_INPUT_DISABLE_TYPE {
    RL78_GPIO_GLOBAL_INPUT_DISABLE_TYPE_ALLOW    = 0,
    RL78_GPIO_GLOBAL_INPUT_DISABLE_TYPE_DISALLOW = 1,
} RL78_GPIO_GLOBAL_INPUT_DISABLE_TYPE;

typedef enum RL78_GPIO_CONTROL_CURRENT {
    RL78_GPIO_CONTROL_CURRENT_TYPE_DIGITAL = 0,
    RL78_GPIO_CONTROL_CURRENT_TYPE_AMPERE = 1,
} RL78_GPIO_CONTROL_CURRENT;

typedef enum RL78_GPIO_AMPERE_SELECTION {
    RL78_GPIO_AMPERE_SELECTION_HIZ = 0,
    RL78_GPIO_AMPERE_SELECTION_2MA = 1,
    RL78_GPIO_AMPERE_SELECTION_5MA = 2,
    RL78_GPIO_AMPERE_SELECTION_10MA = 3,
    RL78_GPIO_AMPERE_SELECTION_15MA = 4,
} RL78_GPIO_AMPERE_SELECTION;

typedef enum RL78_GPIO_DC_LEVEL {
    RL78_GPIO_DC_LEVEL_20MA = 0,
    RL78_GPIO_DC_LEVEL_40MA = 1,
} RL78_GPIO_DC_LEVEL;

typedef enum RL78_GPIO_FUNCTION_OUTPUT {
    RL78_GPIO_FUNCTION_OUTPUT_DISABLE = 0,
    RL78_GPIO_FUNCTION_OUTPUT_ENABLE = 1,
} RL78_GPIO_FUNCTION_OUTPUT;

#define RL78_GPIO_PIN_NUM (8*16)

struct RL78GPIOState {
    /* private */
    SysBusDevice parent_obj;

    /* public */
    MemoryRegion mmio[6];

    qemu_irq outputs[RL78_GPIO_PIN_NUM];

    uint8_t mode[RL78_GPIO_REG_NUM];
    uint8_t level[RL78_GPIO_REG_NUM];
    uint8_t pullup[RL78_GPIO_REG_NUM];
    uint8_t input_mode[RL78_GPIO_REG_NUM];
    uint8_t output_mode[RL78_GPIO_REG_NUM];
    uint8_t digital_input_disable[RL78_GPIO_REG_NUM];
    uint8_t control_a[RL78_GPIO_REG_NUM];
    uint8_t control_t[RL78_GPIO_REG_NUM];
    uint8_t control_e[RL78_GPIO_REG_NUM];
    uint8_t redirection;
    uint8_t global_input_disable;
    uint8_t control_current;
    RL78_GPIO_AMPERE_SELECTION ampere_selections[5];
    uint8_t dc_level;
    uint16_t function_output;

};
typedef struct RL78GPIOState RL78GPIOState;

#define TYPE_RL78_GPIO "rl78-gpio"
DECLARE_INSTANCE_CHECKER(RL78GPIOState, RL78_GPIO, TYPE_RL78_GPIO)

#endif
